version: '3.8'

services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    environment:
      - VITE_API_URL=http://backend:8000/api/v1
    ports:
      - "5173:5173"
    command: npm run dev -- --host


